[Interface]
# Bouncing = 8
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = IIyIC243tUu4rQ48tzbpLcKJAK47Z65ibANVG5krrWs=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# NL-FREE#238
PublicKey = bnzfUDrEjYNRXBwzVTZ7+Y3KQ+wInUNlXWfui88NIwg=
AllowedIPs = 0.0.0.0/0
Endpoint = 185.100.234.177:51820

PersistentKeepalive = 25
