[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = ECaXB4Yzdejm66nzrmjS7WjANqsntW+ORBJFdrb7L20=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CH-FREE#2
PublicKey = 9nrcUUgwvjNU5Z+EBB0C2cbrhQ3dsCz+zSU83/eqGFY=
AllowedIPs = 0.0.0.0/0
Endpoint = 138.199.6.177:51820

PersistentKeepalive = 25
