[Interface]
# Bouncing = 11
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = cPY60R+f+W6yGO5WvssJLi4nb00j86iR+HB5BD+Xy3A=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MX-FREE#2
PublicKey = GU2c5lP3YlUDXt0S+R2BLJXSbLSO76JtqaF7jZSJzDc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 103.88.234.229:51820

PersistentKeepalive = 25