[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = mIWbnYGoY7wTwctDLB852hoUwYTMtmUE1uojudDRFXI=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MX-FREE#14
PublicKey = GLiathVhtMB4GvAwt+0lUxyp8w6FQgCIKrOvr9eh4Fo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 84.20.27.45:51820

PersistentKeepalive = 25