[Interface]
# Bouncing = 4
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = OOT4ZpQ0lDQzNGT7KDg5OqVicjE0fo2KKtWETkQRQlA=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# RO-FREE#29
PublicKey = Hn/oz255qtOjckrUeoA3Gi/UbX/sLSCZPfKXH4lXhjc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.246.146:51820

PersistentKeepalive = 25