[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = GJHS8J3nsexYpRE1feDCK4I4qwbdyDFqc7IuZNQhokQ=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SG-FREE#17
PublicKey = JLHw1UZbc2RQepCk6ZewVl2ipjEh7lvqO4HGFN5NmBU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 103.216.221.71:51820

PersistentKeepalive = 25